# Generated by Django 6.1.1 on 2026-09-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.CharField(max_length=64, unique=True, verbose_name='ID Message Jasmin')),
                ('recipient', models.CharField(max_length=20, verbose_name='Destinataire')),
                ('message', models.TextField(verbose_name='Contenu')),
                ('sender_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Expéditeur')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Transmis à Jasmin'), ('DELIVRD', 'Livré au destinataire'), ('UNDELIV', 'Non livré'), ('REJECTD', 'Rejeté'), ('EXPIRED', 'Expiré'), ('FAILED', 'Échec')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('stat_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Code Jasmin DLR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Historique SMS',
                'verbose_name_plural': 'Historiques SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
